DROP TABLE PERSON;
DROP TABLE JOB;
CREATE TABLE JOB(
    JNO NUMBER(2,0) PRIMARY KEY,
    JNAME VARCHAR2(20) NOT NULL);
CREATE TABLE PERSON(
    ID NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    JNO NUMBER(2,0) REFERENCES JOB(JNO),
    KOR NUMBER(3,0) CHECK(KOR>=0),
    ENG NUMBER(3,0) CHECK(ENG>=0),
    MAT NUMBER(3,0) CHECK(MAT>=0));
DROP SEQUENCE PERSON_SEQ;
CREATE SEQUENCE PERSON_SEQ MAXVALUE 99999 NOCYCLE NOCACHE;
INSERT INTO JOB VALUES (10, '배우');
INSERT INTO JOB VALUES (20, '가수');
INSERT INTO JOB VALUES (30, '개그맨');
COMMIT;
-- 1. 이름, 직업명, 국어, 영어, 수학 입력받아 INSERT
INSERT INTO PERSON 
    VALUES (PERSON_SEQ.NEXTVAL, '정우성', (SELECT JNO FROM JOB WHERE JNAME='배우'),
        99,99,99);
INSERT INTO PERSON 
    VALUES (PERSON_SEQ.NEXTVAL, '박세영', (SELECT JNO FROM JOB WHERE JNAME='배우'),
        90,99,99);
INSERT INTO PERSON 
    VALUES (PERSON_SEQ.NEXTVAL, '배수지', (SELECT JNO FROM JOB WHERE JNAME='가수'),
        90,88,77);
INSERT INTO PERSON 
    VALUES (PERSON_SEQ.NEXTVAL, '송혜교', (SELECT JNO FROM JOB WHERE JNAME='배우'),
        99,99,99);
INSERT INTO PERSON 
    VALUES (PERSON_SEQ.NEXTVAL, '송혜교', 10,
        99,99,99);
--2. 직업명 -> 총점이 많은 것부터 등수로
--등수    이름(ID)   직업   kor    eng   mat    총점
--1등   	송혜교(5번)  배우   100    100  	100	  300
--2등   	정우성(1번)  배우    90    80    	81	  251
SELECT NAME||'('||ID||')' NAMEID, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
    FROM PERSON P, JOB J
    WHERE P.JNO=J.JNO AND JNAME='배우' ORDER BY SUM DESC; -- INLINE-VIEW
SELECT ROWNUM RANK, NAMEID, JNAME, KOR, ENG, MAT, SUM
    FROM (SELECT NAME||'('||ID||')' NAMEID, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
    FROM PERSON P, JOB J
    WHERE P.JNO=J.JNO AND JNAME='배우' ORDER BY SUM DESC);
-- 3번 PERSON테이블의 모든 행을 위와 같이 출력
SELECT ROWNUM RANK, NAMEID, JNAME, KOR, ENG, MAT, SUM
    FROM (SELECT NAME||'('||ID||')' NAMEID, JNAME, KOR, ENG, MAT, KOR+ENG+MAT SUM
    FROM PERSON P, JOB J
    WHERE P.JNO=J.JNO ORDER BY SUM DESC);

SELECT JNAME FROM JOB;







