DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NAME VARCHAR2(20) NOT NULL,
    ID   VARCHAR2(20) PRIMARY KEY,
    PW   VARCHAR2(20) NOT NULL,
    PHONE1 VARCHAR2(10),
    PHONE2 VARCHAR2(10),
    PHONE3 VARCHAR2(10),
    GENDER VARCHAR2(10));
-- 1. 회원가입시
INSERT INTO MEMBER VALUES ('홍길동', 'aaa','111','02','9999','9999','남');
COMMIT;
SELECT * FROM MEMBER;
-- 2. 로그인 시
SELECT * FROM MEMBER WHERE ID='aaa' AND PW='111';
-- 3. 회원정보 수정 시
UPDATE MEMBER SET NAME='홍길', PW='aaa', PHONE1='010', PHONE2='1111', PHONE3='1111',
                GENDER='여' WHERE ID='aaa';
commit;






