DROP TABLE PRODUCT;
CREATE TABLE PRODUCT(
    pNo NUMBER(6) PRIMARY KEY,
    pName VARCHAR2(100) NOT NULL unique,
    pStock NUMBER(3) DEFAULT 0 NOT NULL);
DROP SEQUENCE PRODUCT_SEQ;
CREATE SEQUENCE PRODUCT_SEQ MAXVALUE 999999 NOCACHE NOCYCLE;
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '공책', 10);
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '볼펜', 9);
INSERT INTO PRODUCT VALUES (PRODUCT_SEQ.NEXTVAL, '지우개', 0);
COMMIT;
SELECT * FROM PRODUCT WHERE PNAME='공책';