-- ★ 주요함수=단일행함수 (SQL에서의 함수는 단일행함수와 그룹함수)
SELECT ENAME, TO_CHAR(HIREDATE, 'YY-MM') FROM EMP;
SELECT ENAME, TO_CHAR(SAL, 'L0,000.00') FROM EMP;
SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO;
-- ★ 0. DUAL 테이블 : 산술 연산결과를 얻기위해 오라클에서 제공하는 테스트용 테이블
DESC DUAL;
SELECT * FROM DUAL;
SELECT ABS(-12*4) FROM DUAL;
DESC DUMMY;
SELECT * FROM DUMMY;
SELECT 12*5 FROM DUMMY;
-- ★ 1. 숫자함수
SELECT ABS(-15), -15 FROM DUAL;
SELECT 34.5678, FLOOR(34.5678) FROM DUAL; -- 소수점 이하 버림
SELECT 34.5678, TRUNC(34.5678, 0) FROM DUAL;
SELECT 34.5678, TRUNC(34.5678) FROM DUAL;
SELECT 34.5678, ROUND(34.5678) FROM DUAL; -- 소수점 이하 반올림
SELECT 34.5678, CEIL(34.5678) FROM DUAL; -- 소수점 이하 올림

SELECT 34.5678, TRUNC(34.5678, 3) FROM DUAL;-- 소수점 세번째 자리에서 버림(34.567)
SELECT 34.5678, ROUND(34.5678, 3) FROM DUAL;-- 소수점 세번째 자리에서 반올림(34.568)

SELECT 34.5678, TRUNC(34.5678, -1) FROM DUAL;-- 십의 자리 이하 버림(30)
SELECT 35.5678, ROUND(35.5678, -1) FROM DUAL;-- 십의 자리 이하 반올림

SELECT MOD(9,2) FROM DUAL; -- 자바에서의 9%1
SELECT (2+3)/2 FROM DUAL; -- 2.5
SELECT POWER(2,3) FROM DUAL; -- 2의 3승
SELECT * FROM EMP WHERE MOD(EMPNO, 2)=1;
    -- EMP테이블에서 사번(EMPNO)이 홀수인 사원의 모든 필드를 출력
SELECT MOD('10',2) FROM DUAL;
-- ★ 2. 문자함수
SELECT 'Welcome to Oracle', LOWER('Welcome to Oracle') FROM DUAL; -- 소문자로
SELECT LOWER(ENAME) FROM EMP;
SELECT 'WELcome to oracle', UPPER('WELcome to oracle') FROM DUAL; -- 대문자로
SELECT ENAME, UPPER(ENAME) FROM EMP;
SELECT 'WELCOME TO oracle', INITCAP('WELCOME TO oracle') FROM DUAL; --첫자만 대문자
SELECT ENAME, INITCAP(ENAME) FROM EMP;
SELECT CONCAT('ABC', 'DEF') FROM DUAL; -- ABCDEF
SELECT CONCAT(CONCAT('AB','CD'),'EF') FROM DUAL; -- 'AB'+ 'CD' + 'EF'
SELECT 'AB'||'CD'||'EF' FROM DUAL;
SELECT CONCAT(CONCAT(CONCAT(ENAME, '('),SAL),')') FROM EMP;
    -- 아래의 결과와 동일하게 출력되도록 하고, CONCAT함수를 이용
SELECT ENAME || '(' || SAL || ')' FROM EMP;
    -- EMP테이블에서 이름(급여)
SELECT SUBSTR('Welcome to oracle', 4, 3) FROM DUAL; -- 4번째 글자부터 3글자 추출해
SELECT SUBSTR('Welcome to oracle', -4, 3) FROM DUAL;
SELECT ENAME, SUBSTR(HIREDATE, 1,2) 년, SUBSTR(HIREDATE, 4,2) 월 FROM EMP;
    -- EMP테이블에서 사원의 이름과 입사년, 입사월을 출력
SELECT SUBSTR('WELCOME TO',3,4), SUBSTRB('WELCOME TO', 3, 4) FROM DUAL;
    -- SUBSTR('WELCOME TO',3,4) : 3번째 글자부터 4글자 추출
    -- SUBSTRB('WELCOME TO', 3, 4) : 3번째 BYTE부터 4BYTE 추출
SELECT SUBSTR('웰컴오라클', 3,3), SUBSTRB('웰컴오라클', 3,4) FROM DUAL;
SELECT LENGTH('oRACLE'), LENGTHB('ORACLE') FROM DUAL; -- 글자길이, BYTE길이
SELECT LENGTH('오라클'), LENGTHB('오라클') FROM DUAL;

SELECT INSTR('ABC_ABC_ABC', 'B') FROM DUAL;-- 1번째부터 검색해서 첫 'B'의 위치 출력
SELECT INSTR('ABC_ABC_ABC', 'B', 3) FROM DUAL; -- 3번째부터 검색해서 첫 'B'위치
SELECT INSTR('ABC_ABC_ABC','B',3, 2) FROM DUAL;
    -- 3번째 글자부터 검색해서 2번째 나오는 'B'의 위치
SELECT INSTR('오라오라오라','라') FROM DUAL; -- 2 번째 글자
SELECT INSTR('오라오라오라','라',3) FROM DUAL; -- 4
SELECT INSTR('오라오라오라','라',3,2) FROM DUAL; --6 
SELECT INSTRB('오라오라오라','라') FROM DUAL; -- 4번째 BYTE
SELECT INSTRB('오라오라오라','라',3) FROM DUAL; -- 4번째 BYTE
SELECT INSTRB('오라오라오라','라',3,2) FROM DUAL; --6번째 BYTE
SELECT INSTR('오라오라오라','라',-1) FROM DUAL;

SELECT LPAD('ORACLE', 20,'#') FROM DUAL;
SELECT RPAD('ORACLE', 20, '*') FROM DUAL;
SELECT ENAME, LPAD(SAL, 10, '*') FROM EMP;
SELECT ENAME, RPAD(SAL, 10, '*') FROM EMP;
SELECT RPAD(SUBSTR(ENAME,2,1), LENGTH(ENAME), '*'), SAL FROM EMP;
    -- 이름의 첫글자만 나오고 나머지는 *로 출력 S****, W***, F***, M*****
--탄탄1. 9월에 입사한 사원의 모든 필드를 출력해 보시오
SELECT * FROM EMP WHERE HIREDATE LIKE '%/09/%';
SELECT * FROM EMP WHERE SUBSTR(HIREDATE, 4, 2)='09';
SELECT * FROM EMP WHERE SUBSTR(HIREDATE, 4, 2)=9;
--탄탄2. 83년도에 입사한 직원을 알아내기 위해 SUBSTR 함수를 이용하여 HIREDATE 컬럼에서 
    --첫 글자부터 2개를 추출하여 그 값이 83인지를 체크하는 방법으로도 구해 보도록 하세요. 
SELECT * FROM EMP WHERE HIREDATE LIKE '83%';
SELECT * FROM EMP WHERE SUBSTR(HIREDATE, 1,2)='83';
SELECT * FROM EMP WHERE SUBSTR(HIREDATE, 1,2)=83;
--탄탄3. 다음은 이름이 E로 끝나는 사원을 검색해 보도록 합시다. SUBSTR 함수 이용
SELECT * FROM EMP WHERE SUBSTR(ENAME, -1, 1) ='E';
SELECT * FROM EMP WHERE ENAME LIKE '%E';
--탄탄4. “사번, 이름, JOB(이름의 문자열 수 만큼만 표시)”의 형식의 데이터를 화면에 LIST
    -- 7369   SMITH   CLERK
    -- 7499   ALLEN   SALES
SELECT EMPNO, ENAME, SUBSTR(JOB, 1, LENGTH(ENAME)) FROM EMP;

--탄탄5. EMP 테이블에서 사원이름을 2자리만 출력되고 나머지는 *로 숨기도록 출력
SELECT RPAD(SUBSTR(ENAME, 1, 2), LENGTH(ENAME), '*') FROM EMP;
--탄탄6.	1982년 12월1일 ~1982년12월31일 입사한 사람을 이름과 입사일로 출력;
    -- 날짜형이문자형으로 자동 형변환
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE BETWEEN '82/12/01' AND '82/12/31';
SELECT ENAME, HIREDATE FROM EMP WHERE SUBSTR(HIREDATE, 1, 5)='82/12';

SELECT ENAME, SAL, TRANSLATE(SAL, '0123456789','영일이삼사오육칠팔구') FROM EMP;
SELECT REPLACE('ABCABC','A','X') FROM DUAL;

SELECT TRIM('   ORA CLE  ') T FROM DUAL; -- 좌우 공백 삭제
SELECT LTRIM('   ORA CLE     ') T FROM DUAL;-- 왼쪽 공백 삭제
SELECT RTRIM('   ORA CLE     ') T FROM DUAL;
SELECT TRIM('A' FROM 'AAAAORACLEAAA') FROM DUAL; -- 좌우 'A' 삭제
-- 탄탄 이름의 세번째자리가 R인 사원의 모든 필드를 출력(LIKE, INSTR, SUBSTR)
SELECT * FROM EMP WHERE ENAME LIKE '__R%';
SELECT * FROM EMP WHERE INSTR(ENAME, 'R',3)=3; -- RRRXX까지 포함
SELECT * FROM EMP WHERE SUBSTR(ENAME, 3, 1)='R';

-- ★ 3. 날짜함수
SELECT SYSDATE FROM DUAL; -- SYSDATE : 현시점
SELECT TO_CHAR(SYSDATE, 'MM DD HH24:MI') FROM DUAL;
SELECT SYSDATE-1 "어제요시간", SYSDATE "오늘이시간", SYSDATE+1 "내일요시간" FROM DUAL;
SELECT ENAME, HIREDATE, TRUNC((SYSDATE-HIREDATE)/7) 주수 FROM EMP;
SELECT ENAME, HIREDATE, TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) FROM EMP;
SELECT ADD_MONTHS(SYSDATE, 2) FROM DUAL;
SELECT ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 3) FROM EMP; -- 3달 후
SELECT SYSDATE, NEXT_DAY(SYSDATE, '일') FROM DUAL;
ALTER SESSION SET NLS_LANGUAGE=KOREAN;
            -- SYSDATE로부터 최초로 도래하는 일요일
SELECT SYSDATE, LAST_DAY(SYSDATE) FROM EMP; -- 말일
SELECT ENAME, HIREDATE, LAST_DAY(HIREDATE) 첫월급날 FROM EMP;
-- DATE형의 반올림, 내림
SELECT SYSDATE, ROUND(SYSDATE, 'YEAR') FROM DUAL; -- 'YEAR'로 반올림시 결과는 1월1일
SELECT SYSDATE, ROUND(SYSDATE, 'MONTH') FROM DUAL; -- 'MONTH'로 반올림시 결과는 1일
SELECT SYSDATE, ROUND(SYSDATE, 'DAY') FROM DUAL; -- 'DAY'로 반올림시 결과는 일요일인 날
SELECT ROUND(SYSDATE+2, 'DAY') FROM DUAL;
SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL;
SELECT TRUNC(SYSDATE, 'MONTH') FROM DUAL;
SELECT TRUNC(SYSDATE, 'DAY') FROM DUAL;
SELECT TO_CHAR(TRUNC(SYSDATE), 'MM DD HH24:MI') FROM DUAL;

-- 탄탄1. EMP테이블에서 사원이름과 근무일수, 근무한 주수, 근무개월수, 근무년수를 출력
SELECT ENAME, TRUNC(SYSDATE-HIREDATE) "근무일수",
        TRUNC((SYSDATE-HIREDATE)/7) "근무주수",
        TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) "근무개월수",
        TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)/12) "근무년수" FROM EMP;

-- 탄탄2. EMP테이블에서 사원이름과 입사한 달의 1일을 출력
SELECT ENAME, TRUNC(HIREDATE, 'MONTH') FROM EMP;
-- 탄탄3. EMP테이블에서 사원이름과 입사일과 입사한지 6개월이 지난 시점 출력
SELECT ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 6) FROM EMP;
-- 탄탄4. EMP테이블에서 사원이름과 입사한 달의 말일을 출력
SELECT ENAME, LAST_DAY(HIREDATE) FROM EMP;
-- ★ 4. 형변환함수
-- NUMBER형, DATE형, 문자형
--(1)TO_CHAR(날짜데이터, '형식') :DATE형->문자형
SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY-MM-DD HH:MI:SS') FROM DUAL;
SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY"년"MM"월"DD"일" DY"요일" AM HH:MI:SS') 
    FROM DUAL;
SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY"년"MM"월"DD"일" DAY AM HH24:MI:SS') 
    FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'MON') FROM DUAL;
--(2)TO_CHAR(숫자데이터, '형식') :NUMBER형->문자형
    -- L(로컬통화기호) $ , . 9(자릿수가 없을 땐 채우지 않는다) 0(자리수가 없어도 채움)
SELECT TO_CHAR(SAL, 'L0,000.99') FROM EMP;
SELECT TO_CHAR(123456789, '9,999,999,999') FROM DUAL;
--(3)TO_DATE(문자데이터, '형식') :문자형->DATE형
SELECT HIREDATE FROM EMP;
SELECT * FROM EMP WHERE HIREDATE LIKE '82%';
SELECT * FROM EMP WHERE SUBSTR(HIREDATE, 1,2)=82;
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YY')=82;
-- 1982.10.20에 입사한 직원을 출력
SELECT * FROM EMP WHERE HIREDATE=TO_DATE('19801217','YYYYMMDD');
SELECT * FROM EMP WHERE HIREDATE='82/10/20';
ALTER SESSION SET NLS_DATE_FORMAT='DD-MON-YYYY';
SELECT * FROM EMP WHERE HIREDATE BETWEEN TO_DATE('19821201','YYYYMMDD')
                                AND TO_DATE('19821231','YYYYMMDD');
SELECT TRUNC(SYSDATE - TO_DATE('19931224','YYYYMMDD')) FROM DUAL;
  -- 태어난 날부터 지금까지 몇일이 지난는지 출력
--(4)TO_NUMBER(문자데이터, 형식) : 문자형->NUMBER형
SELECT '1,000'-'500' FROM DUAL;
SELECT TO_NUMBER('1,000', '9,999')-TO_NUMBER('500','999') FROM DUAL;
-- ★ 5. NVL(인자, 인자)
SELECT ENAME, NVL(TO_CHAR(MGR), 'CEO'), TO_CHAR(SAL, '$9,999'), NVL(COMM, 0)
    FROM EMP;
    --EMP 테이블에서 이름, MGR(NULL일 경우 : CEO), SAL($9,999), COMM(NULL일 경우 : 0)
SELECT W.ENAME, NVL(TO_CHAR(W.MGR),'CEO'), NVL(M.ENAME , 'CEO')
    FROM EMP W, EMP M
    WHERE W.MGR=M.EMPNO(+);
    --EMP테이블에서 이름, 상사사번, 상사이름 출력(상사가 없는 경우 상사사번과 이름에 'CEO')
-- ★ 6. DECODE(표현식, 조건1, 값1, 조건2, 값2, 조건3, 값3, 기본값)
SELECT ENAME, DEPTNO, DECODE(DEPTNO, 10, 'ACCOUNTING', 20,'RESEARCH',
                        30, 'SALES', 40,'OPERATIONS', '기본값') AS DNAME FROM EMP;
SELECT ENAME, DEPTNO, 
        CASE WHEN DEPTNO=10 THEN 'ACCOUNTING'
            WHEN DEPTNO=20 THEN 'RESEARCH'
            WHEN DEPTNO=30 THEN 'SALES'
            WHEN DEPTNO=40 THEN 'OPERATIONS'
            ELSE '기본값'
        END
    FROM EMP;
SELECT ENAME, SAL "현재급여", 
    DECODE(JOB, 'ANALYST', SAL*1.1, 'SALESMAN', SAL*1.2, 'MANAGER', SAL*1.3, 
                'CLERK', SAL*1.4, SAL)
    "인상급여" FROM EMP;
    -- JOB에 따라 급여인상을 하도록 한다. JOB 'ANALYST'면 10%인상. 'SALESMAN'면20%인상
    --  'MANAGER'면 30% 인상, 'CLERK' 40%인상
-- ★ 7. 그외 EXTRACT(YEAR FROM 날짜형데이터), LEVEL-START WITH-CONNECT BY PRIOR
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'YYYY')='1982';
SELECT * FROM EMP WHERE EXTRACT(YEAR FROM HIREDATE)=1982;
SELECT * FROM EMP WHERE TO_CHAR(HIREDATE, 'MM')='09';
SELECT * FROM EMP WHERE EXTRACT(MONTH FROM HIREDATE)=9;
-- LEVEL-START WITH-CONNECT BY PRIOR : 계층형 구조를 간단하게 보여주고 싶을 때
SELECT LPAD(' ', 3*(LEVEL-1))||'└'||ENAME, LEVEL, EMPNO, MGR FROM EMP
    START WITH MGR IS NULL
    CONNECT BY PRIOR EMPNO=MGR;

-- ★ 셤 연습문제
--1.현재 날짜를 출력하고 열의 타이틀은 Current Date로 출력하는 SELECT 문장을 기술하시오.
SELECT SYSDATE "Current Date" FROM DUAL;

--2.현재 급여에 15%가 증가된 급여를 사원번호,이름,업무,급여,증가된 급여(New Salary),
    --증가액(Increase)를 출력하는 SELECT 문장을 기술하시오.
SELECT EMPNO, ENAME, JOB, SAL, SAL*1.15 "New Salary", SAL*0.15 Increase FROM EMP;

--3.이름,입사일,입사일로부터 6개월 후 돌아오는 월요일 구하여 출력하는 SELECT 문장을 기술.
SELECT ENAME, HIREDATE, NEXT_DAY(ADD_MONTHS(HIREDATE, 6),'월') FROM EMP;

--4.이름,입사일, 근무개월수,급여, 현재까지 받은 급여의 총계를 출력.
SELECT ENAME, HIREDATE, TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)),SAL,
    SAL*TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE))
        +NVL(COMM,0)*TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)/12)
    FROM EMP;
    
--5.모든 사원의 이름과 급여(15자리로 출력 좌측의 빈 곳은 “*”로 대치)를 출력
SELECT ENAME, LPAD(SAL, 15, '*') FROM EMP;

--6.모든 사원의 정보를 이름,업무,입사일,입사한 요일을 출력
SELECT ENAME, JOB, HIREDATE, TO_CHAR(HIREDATE, 'DY') FROM EMP;

--7.이름의 길이가 6자 이상인 사원의 정보를 이름,이름의 글자수,업무를 출력
SELECT ENAME, LENGTH(ENAME), JOB FROM EMP WHERE LENGTH(ENAME)>=6;

--8.모든 사원의 정보를 이름, 업무, 급여, 보너스, 급여+보너스를 출력
SELECT ENAME, JOB, SAL, COMM, SAL+NVL(COMM, 0) FROM EMP;

--9.사원명에서 2번째 문자부터 3개의 문자를 추출하시오. 
SELECT SUBSTR(ENAME, 2, 3) FROM EMP;

--10.사원 테이블에서 입사일이 12월인 사원의 사번, 사원명, 입사일을 검색하시오
SELECT EMPNO, ENAME, HIREDATE FROM EMP WHERE EXTRACT(MONTH FROM HIREDATE)='12';
SELECT EMPNO, ENAME, HIREDATE FROM EMP WHERE TO_CHAR(HIREDATE, 'MM')='12';

--11.다음과 같은 결과를 검색할 수 있는 SQL 문장을 작성하시오
    --EMPNO		ENAME		급여
    --7369		SMITH		*******800
    --7499		ALLEN		******1600
    --…….
SELECT EMPNO, ENAME, LPAD(SAL, 10, '*') FROM EMP;

--12.다음과 같은 결과를 검색할 수 있는 SQL 문장을 작성하시오
    --EMPNO	 ENAME 	입사일
    --7369	  SMITH		1980-12-17
    --...
SELECT EMPNO, ENAME, TO_CHAR(HIREDATE, 'YYYY-MM-DD') FROM EMP;

--13.사원 테이블에서 급여에 따라 사번, 이름, 급여, 등급을 검색하는 SQL 문장을 작성 하시오. 
-- 급여가 0~1000 E / 1001~2000 D / 2001~3000 C / 3001~4000 B / 4001~5000 A
SELECT EMPNO, ENAME, SAL, DECODE(TRUNC((SAL-1)/1000), 0,'E', 1,'D',2,'C',
                                            3,'B', 4, 'A') FROM EMP;
SELECT EMPNO, ENAME, SAL,
    CASE WHEN SAL>=0 AND SAL<=1000 THEN 'E'
        WHEN SAL>=1001 AND SAL<=2000 THEN 'D'
        WHEN SAL>=2001 AND SAL<=3000 THEN 'C'
        WHEN SAL>=3001 AND SAL<=4000 THEN 'B'
        WHEN SAL>=4001 AND SAL<=5000 THEN 'A'
    END FROM EMP;    
   --(cf) 급여가- 0~999 E / 1000~1999 D / 2000~2999 C / 3000~3999 B / 4000이상 A
SELECT EMPNO, ENAME, SAL, DECODE(TRUNC(SAL/1000), 0,'E', 1,'D',2,'C',
                                            3,'B', 'A') 등급 FROM EMP;
SELECT EMPNO, ENAME, SAL,
    CASE WHEN SAL>=0 AND SAL<=999 THEN 'E'
        WHEN SAL>=1000 AND SAL<=1999 THEN 'D'
        WHEN SAL>=2000 AND SAL<=2999 THEN 'C'
        WHEN SAL>=3000 AND SAL<=3999 THEN 'B'
        WHEN SAL>=4000 AND SAL<=4999 THEN 'A'
    END 등급 FROM EMP;

--14. 사원 테이블에서 부서번호가 20인 사원의 사번, 이름, 직무, 급여를 출력하시오
    --(급여는 앞에 $를 삽입하고 3자리마다 ,를 출력한다)
SELECT EMPNO, ENAME, JOB, TO_CHAR(SAL, '$9,999,999') FROM EMP WHERE DEPTNO=20;










