-- 그룹함수 ( SUM, AVG, COUNT, MAX, MIN, STDDEV, VARIANCE)
-- ★ 1. 그룹함수에 대하여
SELECT SUM(SAL) FROM EMP;
SELECT TO_CHAR(SUM(SAL), '$999,999') FROM EMP;
SELECT SUM(COMM) FROM EMP; -- 그룹함수는 NULL을 제외하고 수행
SELECT COMM FROM EMP;
SELECT COUNT(*) FROM EMP;
SELECT COUNT(SAL) FROM EMP;
SELECT COUNT(COMM) FROM EMP;
SELECT SUM(ENAME) FROM EMP; -- 문자형은 SUM, AVG, STDDEV, VARIANCE은 불가
SELECT SUM(HIREDATE) FROM EMP;-- DATE형은 SUM, AVG, STDDEV, VARIANCE은 불가
SELECT AVG(SAL), SUM(SAL)/COUNT(SAL) FROM EMP;
SELECT AVG(COMM), SUM(COMM)/COUNT(COMM) FROM EMP;
SELECT MAX(SAL), MIN(SAL) FROM EMP; -- MAX, MIN은 모든 자료형에서 가능
SELECT MIN(HIREDATE), MAX(HIREDATE) FROM EMP;
SELECT MIN(ENAME), MAX(ENAME) FROM EMP;
SELECT ROUND(AVG(SAL),2), ROUND(VARIANCE(SAL),2), ROUND(STDDEV(SAL),2) FROM EMP;
SELECT SAL FROM EMP;
SELECT SQRT(VARIANCE(SAL)), STDDEV(SAL) FROM EMP;
SELECT VARIANCE(SAL), STDDEV(SAL)*STDDEV(SAL) FROM EMP;
SELECT COUNT(DISTINCT JOB) FROM EMP;
SELECT DISTINCT JOB FROM EMP;
SELECT COUNT(DISTINCT  DEPTNO) FROM EMP;
--탄탄1. 최근입사일, 최근입사한사람의근무일수
SELECT MAX(HIREDATE), TRUNC(SYSDATE-MAX(HIREDATE)) FROM EMP;
--탄탄1-1. 최초입사일, 최초입사일한사람의 근무일수
SELECT MIN(HIREDATE), TO_CHAR(TRUNC(SYSDATE-MIN(HIREDATE)), '99,999') FROM EMP;
--탄탄2. 10번 부서의 사원들 중에서 상여금(COMM)을 있는 사원의 수
SELECT COUNT(COMM) FROM EMP WHERE DEPTNO=10;
SELECT COUNT(*) FROM EMP WHERE DEPTNO=10 AND COMM IS NOT NULL;
-- ★ 2. GROUP BY 절 : 그룹함수를 쓰되 어떤 컬럼값을 기준으로 그룹함수를 적용하고자 할 때
    -- GROUP BY 절에는 별칭을 사용할 수 없고 컬럼명이나 컬럼명을 이용한 연산
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO;
SELECT * FROM DEPT;
SELECT DEPTNO, AVG(SAL), DECODE(DEPTNO, 10, 'ACCOUNTING',
                                        20, 'RESEARCH',
                                        30, 'SALES',
                                        'OPERATIONS') FROM EMP GROUP BY DEPTNO;
SELECT DEPTNO 부서, AVG(SAL), STDDEV(SAL) FROM EMP 
        WHERE DEPTNO != 10
        GROUP BY DEPTNO
        ORDER BY 부서;
SELECT EXTRACT(YEAR FROM HIREDATE), AVG(SAL) FROM EMP 
        GROUP BY EXTRACT(YEAR FROM HIREDATE);
-- 탄탄다지기 : 부서명별로 평균급여를 검색하시오.
SELECT DNAME, AVG(SAL) FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO GROUP BY DNAME;
-- ★ 3. HAVING 절 : 그룹함수에 대한 조건절
SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO HAVING AVG(SAL)>2000;

-- ★ 4. 피벗테이블
SELECT JOB, SUM(SAL) FROM EMP GROUP BY JOB;
SELECT JOB, SUM(SAL) FROM EMP GROUP BY ROLLUP(JOB);
SELECT JOB, AVG(SAL) FROM EMP GROUP BY ROLLUP(JOB);
SELECT AVG(SAL) FROM EMP;
SELECT DEPTNO, JOB, SUM(SAL) FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO;
SELECT DEPTNO, JOB, SUM(SAL) FROM EMP GROUP BY ROLLUP(DEPTNO, JOB);
SELECT JOB, DEPTNO, SUM(SAL) FROM EMP GROUP BY JOB, DEPTNO;

SELECT DEPTNO, JOB, SUM(SAL) FROM EMP GROUP BY DEPTNO, JOB 
    ORDER BY DEPTNO, JOB; -- 가독성을 높기 위해 피벗
SELECT DEPTNO, SUM(DECODE(JOB, 'CLERK', SAL, 0)) "CLEARK",
               SUM(DECODE(JOB, 'MANAGER', SAL, 0)) "MANAGER",
               SUM(DECODE(JOB, 'PRESIDENT', SAL, 0)) "PRESIDENT",
               SUM(DECODE(JOB, 'ANALYST', SAL, 0)) "ANALYST",
               SUM(DECODE(JOB, 'SALESMAN',SAL, 0)) "SALESMAN",
               SUM(SAL) "소계" FROM EMP
        GROUP BY ROLLUP(DEPTNO);
               
--     CLERK MANAGER PRESIDENT ANALYST SALESMAN
-- 10   1300  2450      5000      0        0
-- 20   1900     0         0     6000
-- 30





-- ★ 셤연습문제
--1.사원 테이블에서 인원수,최대 급여,최소 급여,급여의 합을 계산하여 출력
SELECT COUNT(*), MAX(SAL), MIN(SAL), SUM(SAL) FROM EMP;

--2.사원테이블에서 업무별 인원수를 구하여 출력
SELECT JOB, COUNT(*) FROM EMP GROUP BY JOB;

--3.사원테이블에서 최대 급여와 최소 급여의 차이는 얼마인가 출력
SELECT MAX(SAL)-MIN(SAL) FROM EMP;

--4.부서별로 인원수, 급여 평균, 최저 급여, 최고 급여, 급여의 합을 출력하되 
    --급여의 합이 많은 순으로 출력
SELECT DEPTNO, COUNT(*), AVG(SAL), MIN(SAL), MAX(SAL), SUM(SAL) 합 FROM EMP 
    GROUP BY DEPTNO
    ORDER BY 합 DESC;

--5.부서별, 업무별 그룹하여 결과를 부서번호, 업무, 인원수, 급여의 평균, 급여의 합을 구하여 출력
    --(출력결과는 부서번호, 업무순으로 오름차순 정렬)
SELECT DEPTNO, JOB, COUNT(*), AVG(SAL), SUM(SAL) FROM EMP
    GROUP BY DEPTNO, JOB ORDER BY DEPTNO, JOB;
    
--6.업무별, 부서별 그룹하여 결과를 부서번호, 업무, 인원수, 급여의 평균, 급여의 합을 구하 출력하라.
    --(출력결과는 업무순, 부서번호 순 오름차순 정렬)
SELECT DEPTNO, JOB, COUNT(*), AVG(SAL), SUM(SAL) FROM EMP
    GROUP BY JOB, DEPTNO ORDER BY JOB, DEPTNO;
    
--7.사원수가 5명이상 넘는 부서번호와 사원수 출력
SELECT DEPTNO, COUNT(*) FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>=5;

--8. 사원수가 5명이상 넘는 부서명과 사원수를 출력
SELECT DNAME, COUNT(*) FROM EMP E, DEPT D
    WHERE E.DEPTNO=D.DEPTNO
    GROUP BY DNAME HAVING COUNT(*)>=5;
    
--9. 업무별 급여의 평균이 3000이상인 업무에 대해서 업무명, 평균 급여, 급여합 출력
SELECT JOB, AVG(SAL), SUM(SAL) FROM EMP GROUP BY JOB HAVING AVG(SAL)>=3000;

--10.전체 급여가 5000을 초과하는 각 업무에 대해서 업무와 급여합계를 출력.
    --단, 급여 합계로 내림차순 정렬
SELECT JOB, SUM(SAL) FROM EMP 
    GROUP BY JOB  HAVING SUM(SAL)>5000 ORDER BY SUM(SAL) DESC;
    
--11.부서별 급여평균, 부서별 급여합계, 부서별 최소급여를 출력
SELECT DEPTNO, AVG(SAL), SUM(SAL), MIN(SAL) FROM EMP GROUP BY DEPTNO;

--12. 위의 11번을 수정하여, 부서별 급여평균 최대치, 부서별 급여합의 최대치, 
    --부서별 최소급여의 최대치를 출력하라
SELECT MAX(AVG(SAL)), MAX(SUM(SAL)), MAX(MIN(SAL)) FROM EMP GROUP BY DEPTNO;

--13. 
    --H_YEAR	COUNT(*)	MIN(SAL)	MAX(SAL)	AVG(SAL)	SUM(SAL)
    --		80	  1		    800		    800		    800		    800
    --		81	 10		    950		    5000		2282.5		22825
    --		82	  2		    1300		3000		2150		4300
    --		83	  1		    1100		1100		1100		1100
SELECT TO_CHAR(HIREDATE, 'YY') H_YEAR, 
        COUNT(*), MIN(SAL), MAX(SAL), AVG(SAL), SUM(SAL)
    FROM EMP GROUP BY TO_CHAR(HIREDATE, 'YY');
    
--14.피벗아닌 거 부터
SELECT TO_CHAR(HIREDATE, 'YYYY'), COUNT(*) FROM EMP 
    GROUP BY TO_CHAR(HIREDATE, 'YYYY');
    
SELECT TO_CHAR(HIREDATE, 'YYYY'), COUNT(*) FROM EMP 
    GROUP BY ROLLUP(TO_CHAR(HIREDATE, 'YYYY'));
    
SELECT NVL(TO_CHAR(HIREDATE, 'YYYY'),'TOTAL'), COUNT(*) FROM EMP 
    GROUP BY ROLLUP(TO_CHAR(HIREDATE, 'YYYY'));
--피벗은 나중에
    --TOTAL		1980	1981	1982	1983
    --14		1	    10	    2	    1
-- 피벗이전단계
SELECT DECODE(EXTRACT(YEAR FROM HIREDATE), 1980, 1, 0) "1980",
       DECODE(EXTRACT(YEAR FROM HIREDATE), 1981, 1, 0) "1981",
       DECODE(EXTRACT(YEAR FROM HIREDATE), 1982, 1, 0) "1982",
       DECODE(EXTRACT(YEAR FROM HIREDATE), 1983, 1, 0) "1983" FROM EMP;
-- 피벗
SELECT COUNT(*) TOTAL,
       SUM(DECODE(EXTRACT(YEAR FROM HIREDATE), 1980, 1, 0)) "1980",
       SUM(DECODE(EXTRACT(YEAR FROM HIREDATE), 1981, 1, 0)) "1981",
       SUM(DECODE(EXTRACT(YEAR FROM HIREDATE), 1982, 1, 0)) "1982",
       SUM(DECODE(EXTRACT(YEAR FROM HIREDATE), 1983, 1, 0)) "1983" FROM EMP;
       
--15.사원테이블에서 아래의 결과를 출력하는 SELECT 문 작성(JOB 순으로 오름차순 정렬)
--피벗아닌 거부터
SELECT JOB, DEPTNO, SUM(SAL) FROM EMP 
    GROUP BY ROLLUP(JOB, DEPTNO) ORDER BY JOB, DEPTNO;
    
--피벗은 나중에
    --JOB		DEPTNO10	DEPTNO20	DEPTNO30     TOTAL
    --ANALYST	     0		   6000		    0		6000
    --CLERK		  1300		   1900		  950		4150
    --….
    --SALESMAN	      0	 		0	    5600		 5600
--피벗이전단계 - DECODE
SELECT JOB, DECODE(DEPTNO, 10, SAL, 0) DEPTNO10,
            DECODE(DEPTNO, 20, SAL, 0) DEPTNO20,
            DECODE(DEPTNO, 30, SAL, 0) DEPTNO30 FROM EMP;
-- 피벗 (적절한 그룹함수 이용)
SELECT JOB, SUM(DECODE(DEPTNO, 10, SAL, 0)) DEPTNO10,
            SUM(DECODE(DEPTNO, 20, SAL, 0)) DEPTNO20,
            SUM(DECODE(DEPTNO, 30, SAL, 0)) DEPTNO30,
            SUM(SAL) TOTAL FROM EMP GROUP BY JOB;
            
--(16)	 사원테이블에서 최대급여, 최소급여, 전체급여합, 평균을 구하시오
SELECT MAX(SAL), MIN(SAL), SUM(SAL), AVG(SAL) FROM EMP;	

--(17)	 사원테이블에서 부서별 인원수를 구하시오
SELECT DEPTNO, COUNT(*) FROM EMP GROUP BY DEPTNO;

--(18)	 사원 테이블에서 부서별 인원수가 6명이상인 부서코드를 구하시오
SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>=6;

--(19)	 사원테이블에서 다음과 같은 결과가 나오게 하시오
--피벗 아닌거 먼저
SELECT DNAME, JOB, SUM(SAL) FROM EMP E, DEPT D 
    WHERE E.DEPTNO=D.DEPTNO GROUP BY DNAME, JOB ORDER BY DNAME;
    --DNAME               CLERK    MANAGER   PRESIDENT    ANALYST   SALESMAN
    --ACCOUNTING            1300       2450       5000          0          0
    --RESEARCH              1900       2975          0       6000          0
    --SALES                 950        2850          0          0       5600
--피벗 나중에
SELECT DNAME, SUM(DECODE(JOB, 'CLERK', SAL, 0)) "CLERK",
              SUM(DECODE(JOB, 'MANAGER', SAL, 0)) "MANAGER",
              SUM(DECODE(JOB, 'PRESIDENT', SAL, 0)) "PRESIDENT",
              SUM(DECODE(JOB, 'ANALYST', SAL, 0)) "ANALYST",
              SUM(DECODE(JOB, 'SALESMAN', SAL, 0)) "SALESMAN" FROM EMP E, DEPT D
            WHERE E.DEPTNO=D.DEPTNO
            GROUP BY DNAME;

--(20)사원테이블에서 급여가 높은 순서대로 등수를 부여하여 다음과 같은 결과가 나오게 하시오.
        --(힌트 self join, group by, count사용)
    --	ENAME	    등수
    --	________________________
    --	KING		1
    --	SCOTT		2
    --	FORD		2
    --	JONES		4
    --	……
SELECT E1.ENAME, E2.ENAME FROM EMP E1, EMP E2
    WHERE E1.SAL<E2.SAL AND E1.ENAME='SCOTT';

SELECT E1.ENAME, COUNT(E2.ENAME)+1 RANK FROM EMP E1, EMP E2
    WHERE E1.SAL<E2.SAL(+) GROUP BY E1.ENAME 
    ORDER BY RANK;











