-- 인덱스
DROP TABLE EMP1;
CREATE TABLE EMP1 AS SELECT * FROM EMP;
SELECT * FROM EMP1;
INSERT INTO EMP1 VALUES (1111, 'HONG',NULL, NULL,SYSDATE,NULL,NULL,40);
INSERT INTO EMP1 SELECT * FROM EMP;
SELECT COUNT(*) FROM EMP1;
SELECT COUNT(*) FROM EMP1 WHERE ENAME='HONG';
INSERT INTO EMP1 SELECT * FROM EMP1;
DESC EMP1;
SELECT EMPNO, ENAME, SAL FROM EMP1 WHERE ENAME='HONG';
CREATE INDEX IDX_EMP1_ENAME ON EMP1(ENAME);
    -- INSERT, UPDATE, DELETE 거의 쓰지 않고, ENAME으로 검색하는 경우 90%이상일 때 인덱스






